### ISSUE TITLE
Move this to RedwoodJS org?

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/docker#10]
@jeliasson should we consider moving this repo to the RedwoodJS GitHub org? You (and anyone else) could still be the admins. I'm just thinking it might provide greater visibility and findability.

Up to you.

**Comment by jeliasson** [comment]
@thedavidprice Definitely. This repo is/was just to kick-start the testing. I'll transfer it to redwoodjs org in a couple of minutes. After that, we need credentials to write to a Container Registry - suggestively [GitHub Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry). 

https://github.com/jeliasson/redwoodjs-docker/blob/94e75f11408dbd2558dd6b102edf589cda9d5a95/.github/workflows/template.yml#L62-L64

/cc @realStandal @ajcwebdev

**Comment by jeliasson** [comment]
Hmm. I have never transferred a repository to an organisation on which I don't have admin access to. 
@thedavidprice Ideas? I'll have a closer look in an hour.

![image](https://user-images.githubusercontent.com/865493/159325918-636e4907-3d66-427b-bc16-3826bcd76ef3.png)
![image](https://user-images.githubusercontent.com/865493/159325836-a772eb8c-7dd4-4f76-87a9-45418595b11c.png)

**Comment by thedavidprice** [comment]
@jeliasson add me as Admin here?

**Comment by thedavidprice** [comment]
> After that, we need credentials to write to a Container Registry - suggestively [GitHub Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry).

Sure thing.

**Comment by jeliasson** [comment]
> @jeliasson add me as Admin here?

Is that possible on private repositories? Maybe we'll have to create a interim transfer org 😅
![image](https://user-images.githubusercontent.com/865493/159335251-d6de23ca-0c4e-471f-8703-414e04c07030.png)

**Comment by jeliasson** [comment]
@thedavidprice Repository transferred to temporary org `redwoodjsdocker`, and an invitation should be in your mailbox. 
Can you initialize the transfer? 👑

**Comment by thedavidprice** [comment]
Done! 

@jeliasson I'll let you handle additional permissions.

<img width="780" alt="Screen Shot 2022-03-21 at 4 09 44 PM" src="https://user-images.githubusercontent.com/2951/159377705-8444efa0-b32c-40ce-821f-045a4671be64.png">
