### ISSUE TITLE
Minor changes after repository move

### ISSUE THREAD

**Issue by jeliasson** [redwoodjs/docker#12]
Things that needs some attention;

- [x] Activate GitHub Container Registry on the redwoodjs org if not already activated
- [x] Setup a new Personal Access Token or something for secret `CONTAINER_REGISTRY_PASSWORD`
- [x] Update GitHub actions to push images to redwoodjs and maybe rename images
- [x] Verify that build goes thru
- [x] Update documentation

**Comment by thedavidprice** [comment]
@jeliasson Does this look correct?

<img width="447" alt="Screen Shot 2022-03-25 at 9 17 22 AM" src="https://user-images.githubusercontent.com/2951/160159893-5f503e77-d057-412e-a893-fb74c8241ef7.png">

## Token
<img width="719" alt="Screen Shot 2022-03-25 at 9 19 46 AM" src="https://user-images.githubusercontent.com/2951/160160309-7bdb7f83-4cc6-4932-8279-79209822f537.png">

###
I've updated value for `CONTAINER_REGISTRY_PASSWORD`

**Comment by jeliasson** [comment]
@thedavidprice Looks great, thank you!
