### ISSUE TITLE
api server dependecy can be out of sync from local install

### ISSUE THREAD

**Issue by callingmedic911** [redwoodjs/docker#14]
I'm also using a similar Docker implementation in production and ran into a busted dependency and was unable to reproduce locally. Figured the production is running a different version (because no .lock file). I understand the .lock is for whole workspace, but copying over may ensure that at least api deps are pinned to the same version as locally.

Just to be clear, we probably want to keep yarn.lock in the last stage of docker build. Just before: https://github.com/redwoodjs/docker/blob/main/docker/standal-ce-nginx/api/Dockerfile#L35

cc: @realStandal

**Comment by realStandal** [comment]
Much appreciated!

I don't think it's going to hurt to include the `yarn.lock` in the final "Serve" stage, but I do want to make sure a rudimentary benchmark is done to make sure the final image size isn't dramatically increased.

Even though, if it is, there isn't much that can be done (maybe until Yarn3)

**Comment by jeliasson** [comment]
Closing issue in preparation for archiving.
