### ISSUE TITLE
Define image name and tags

### ISSUE THREAD

**Issue by jeliasson** [redwoodjs/docker#15]
This issue seeks to define what image name and tags that should be used when building (and publishing images for official releases).

### Official releases
Officially supported and built images that would be published to a Container Registry, and registered with e.g. Docker Hub.

**Suggestions**
1. With redwood prefix
- `redwoodjs/redwood:<version>`, e.g. `redwoodjs/redwood:0.49.1` - both
- `redwoodjs/redwood-api:<version>`, e.g. `redwoodjs/redwood-api:0.49.1` - api
- `redwoodjs/redwood-web:<version>`, e.g. `redwoodjs/redwood-web:0.49.1` - web

2. Without redwood prefix
- `redwoodjs/both:<version>`, e.g. `redwoodjs/both:0.49.1` - both
- `redwoodjs/api:<version>`, e.g. `redwoodjs/api:0.49.1` - api
- `redwoodjs/web:<version>`, e.g. `redwoodjs/web:0.49.1` - web

3. _[Adding more as suggestions come in]_ 

**Other**
- [ ] Should images also be build from the main branch, with e.g. `:<sha>` as tag?

### Development
Development/testing built images that would be published to a Container Registry

**Suggestions**
1. Sha
- `redwoodjs/redwood-<implementation name>-[api/both/web]:<sha>`, e.g. `redwoodjs/redwood-jeliasson-nginx-web:94e75f1`
- `redwoodjs/redwood-<implementation name>-[api/both/web]:<sha>`, e.g. `redwoodjs/redwood-standal-ce-nginx-web:94e75f1`

2. _[Adding more as suggestions come in]_

**Comment by jeliasson** [comment]
> The main branch having its own build seems useful for QA - PRs too/instead?

Yes (my only question under _Other_ so far) and PR build would be neat. cc @Tobbe 🧙🏻‍♂️

> What about having ones which match Redwood's [npm tags](https://www.npmjs.com/package/@redwoodjs/core)? (`latest`, `rc`)

I don't think `latest` is available, but +1 to match to npm tags and releases, including rc's. When stable and with  _Core-team seal of approval_ ™, it could be part of the regular release cycle/workflows.

**Comment by Tobbe** [comment]
> Yes (my only question under _Other_ so far) and PR build would be neat. cc @Tobbe 🧙🏻‍♂️

Yeah, sometimes I miss those PR builds. Bummer I couldn't get them to be more reliable 🙁
