### ISSUE TITLE
Define official Docker images

### ISSUE THREAD

**Issue by jeliasson** [redwoodjs/docker#16]
This issue seeks to define what official RedwoodJS Docker images should be supported and maintained by the community.

### Production
Discussion on Dockerfiles and it's implementation

**Suggestions**

1. One image
  - `yarn rw serve` - example [`standal-cli-both`](https://github.com/redwoodjs/docker/blob/main/docker/standal-cli-both/both/Dockerfile)
2. Two images
  - api - example [`standal-ce-nginx`](https://github.com/redwoodjs/docker/blob/main/docker/standal-ce-nginx/api/Dockerfile), [`jeliasson-nginx`](https://github.com/redwoodjs/docker/blob/main/docker/jeliasson-nginx/api/Dockerfile)
  - web - example [`standal-ce-nginx`](https://github.com/redwoodjs/docker/blob/main/docker/standal-ce-nginx/web/Dockerfile), [`jeliasson-nginx`](https://github.com/redwoodjs/docker/blob/main/docker/jeliasson-nginx/web/Dockerfile)

2. _[Adding more as suggestions come in]_

### Overall
- [ ] Define official image(s) path
- [ ] Review and feedback from community and hosting providers
- [ ] If possible, use `yarn rw-server api` over `yarn rw serve api`

### Build tracking

| Workflow | Build status |
| --------- | ------------- |
| `standal-ce-nginx` | [![standal-ce-nginx](https://github.com/redwoodjs/docker/actions/workflows/standal-ce-nginx.yml/badge.svg)](https://github.com/redwoodjs/docker/actions/workflows/standal-ce-nginx.yml) |
| `standal-cli-both` | [![standal-cli-both](https://github.com/redwoodjs/docker/actions/workflows/standal-cli-both.yml/badge.svg)](https://github.com/redwoodjs/docker/actions/workflows/standal-cli-both.yml) | 
| `jeliasson-nginx` | [![jeliasson-nginx](https://github.com/redwoodjs/docker/actions/workflows/jeliasson-nginx.yml/badge.svg)](https://github.com/redwoodjs/docker/actions/workflows/jeliasson-nginx.yml) |

**Comment by realStandal** [comment]
Just to confirm, these would be images which an application would extend `FROM` in its `Dockerfile`?

Just a thought, what if we support an `eject` command which gives the application the "bare" Dockerfile, should they require it? (I haven't done too much to modify existing images, so I'm not sure if that's an acceptable route and we don't need `eject` - feel free to educate). Some way to extend the base image or redefine it, depending on the needs of an app. Perhaps this covers the "special Dockerfiles"?

I'm tempted to suggest `docker-compose.yml` be a separate feature to what we're discussing here. What we're discussing here feels like "the setup and steps to build (a basic?) RW application into an image". Compose, I think, could be considered a deployment target to run that image as a container, alongside K8s, KNative, EKS, ...

**Comment by realStandal** [comment]
There are two things that kinda "stump" me:

- Are we going to choose Nginx and say "this is Redwood's official way of containerizing your web-side"
  - Using Nginx, Caddy, or even [`http-server`](https://www.npmjs.com/package/http-server) is going to [_dramatically_ reduce the final image size](https://community.redwoodjs.com/t/dockerize-redwoodjs/2291/7?u=realstandal), but do we want to write off a choice as "Redwood's opinion, deal with it"?
- Are we going to say it's `web-nginx`, and allow for other builds (`web-caddy`, `web-rw-server`, ...)

I _think_ the API makes the decision for us. Using `rw-server api` is [probably going to be the most viable `ENTRYPOINT`](https://github.com/redwoodjs/redwood/pull/4856#issuecomment-1075596428).

**Comment by jeliasson** [comment]
> [...] I don't think its high priority though, since this repo is a good enough resource, and people will likely need customization until we find the best "out-of-the-box" solution

Agreed

> [...] You have to install everything anyways, unless there is a way to cherry-pick only new dependencies

I guess there could be some build time to save, if the base image would only hold some dependencies to copy in, but ultimately might just be a headache to maintain. I'll see if I can throw together something.

>  [...] Tangentially related example: I just had an issue with redwood version mismatch in a global install vs the app.

Yeah, thanks for creating that issue. While I don't mind switching over to canary from time to time, I ended up doing this to globally install with the appropriate version. 

```Dockerfile
[...]

# Install jq
RUN apk update && apk add jq && rm -rf /var/cache/apk/*

# Get Redwood version from api/package.json and it's @redwoodjs/api dependency
# Also, let's remove potential `^` character from the version.
RUN RW_VERSION=$(jq -r '.dependencies["@redwoodjs/api"]' api/package.json | sed 's/\^//')

# Install dependencies
RUN yarn install

# Install additional dependencies
RUN yarn add @redwoodjs/api-server@${RW_VERSION} @redwoodjs/internal@${RW_VERSION}

[...]
```

**Comment by jeliasson** [comment]
Closing issue in preparation for archiving.
