### ISSUE TITLE
Support Yarn 3 across images

### ISSUE THREAD

**Issue by realStandal** [redwoodjs/docker#19]
CC - @jeliasson, @callingmedic911

I noticed [in the Actions logs](https://github.com/redwoodjs/docker/runs/5625847024?check_suite_focus=true#step:5:181) that (at least) the `standal-*` images aren't using Yarn 3. This issue is to track its implementation, and provide an explanation should any additional steps be needed.

I'm also _really_ interested in the new build-time, as I think installation is the biggest pain-point right now.

**Comment by jeliasson** [comment]
@callingmedic911's implementation looks interesting. I will give this a try.
https://gist.github.com/callingmedic911/15e87c3d26cd4c2c22cad780ff832f75

**Comment by jeliasson** [comment]
Closing issue in preparation for archiving.
