### ISSUE TITLE
Define docker-compose files

### ISSUE THREAD

**Issue by jeliasson** [redwoodjs/docker#20]
This issue seeks to define what docker-compose files should be supported and maintained by the community.

### Dependencies
- [ ] [Define official Docker image(s)](https://github.com/redwoodjs/docker/issues/16)

### Development

_WiP_

### Production

_WiP_

### References
- [`ajcwebdev/redwood-docker-compose`](https://github.com/ajcwebdev/redwood-docker-compose) (💀 dead)
- [`pi0neerpat`](https://github.com/redwoodjs/docker/blob/169a704a3987bfe03acbe165e652c00be540a909/docker/pi0neerpat-packages/docker-compose.yml)

**Comment by pi0neerpat** [comment]
I added my docker-compose here: https://github.com/redwoodjs/docker/blob/169a704a3987bfe03acbe165e652c00be540a909/docker/pi0neerpat-packages/docker-compose.yml

**Comment by jeliasson** [comment]
Closing issue in preparation for archiving.
