### ISSUE TITLE
Community: How does your Dockerfile(s) look like?

### ISSUE THREAD

**Issue by jeliasson** [redwoodjs/docker#21]
In the quest 🧙🏻‍♂️ of finding a good path to officially dockerize and support Redwood image(s) we ask for your help.

If you have a production or experimental Docker setup;

1. Kindly share your Dockerfile(s)
2. Bonus points for a PR that [adds the implementation](https://github.com/redwoodjs/docker#development) to the testing, or indicate if the repository maintainers can bring it in on your behalf. No pressure.

#### References
- [Implementations](https://github.com/redwoodjs/docker#implementations) for current implementations tests and builds.
- [Dockerize RedwoodJS](https://community.redwoodjs.com/t/dockerize-redwoodjs) on the community forums

Thanks!

**Comment by noire-munich** [comment]
Ah, thanks for the post @jeliasson ! I meant to get in touch a while back as DP told me your interest in this.

Here's what we're using:

```
# First we build.
FROM node:16.6.1-alpine as build

WORKDIR /app

COPY package*.json yarn.lock redwood.toml graphql.config.js .env ./

COPY api api

COPY web web

RUN yarn install --frozen-lockfile

RUN yarn rw build && yarn rw record init && cp .redwood/datamodel.json datamodel.json

# COPY --from=build /app/node_modules /app/node_modules

FROM node:16.6.1-alpine as serve

WORKDIR /app

COPY package*.json redwood.toml graphql.config.js ./

RUN mkdir .redwood

COPY --from=build /app/datamodel.json /app/.redwood/datamodel.json

COPY --from=build /app/api/db /app/api/db

COPY --from=build /app/web/dist /app/web/dist

COPY --from=build /app/api/dist /app/api/dist

COPY --from=build /app/node_modules/.prisma /app/node_modules/.prisma

COPY --from=build /app/node_modules /app/node_modules

EXPOSE 8910 8911

ENTRYPOINT yarn rw serve
```

It's in our CI workflow and we deploy to AWS Beanstalk.

**Comment by jeliasson** [comment]
Closing issue in preparation for archiving.
